<#
.SYNOPSIS
    Deploys a deployment package group to a target Dataverse environment.

.DESCRIPTION
    Authenticates the pac CLI with the target environment using GitHub OIDC federated
    credentials, then invokes pac package deploy on the managed package ZIP.

    Per-solution deployment settings files (generated by Generate-DeploymentSettings.ps1
    and downloaded as release assets) are merged and transformed into the semicolon-delimited
    key=value string that pac package deploy --settings expects:

      ConnectionReferences[].LogicalName → ConnectionId
      EnvironmentVariables[].SchemaName  → Value

    All settings files for the package group and target environment are merged; duplicate
    keys are deduplicated (last writer wins — values are identical across solutions for the
    same environment).

.PARAMETER packageGroup
    Name of the package group (e.g. "MySolution_Package"). Used to locate the managed ZIP.

.PARAMETER solutions
    Comma-separated list of solution names within the package group. Used only to locate
    the per-solution settings files — pac package deploy handles deploy order internally
    via the package's ImportConfig.xml.
    Example: "pub_MySolution,pub_AnotherSolution"

.PARAMETER targetEnvironment
    Logical environment name (e.g. "myapp-test"). Used to locate settings files.

.PARAMETER environmentUrl
    Target Dataverse environment URL (e.g. "https://myapp-tst-contoso.crm.dynamics.com/").

.PARAMETER tenantId
    Azure AD tenant ID.

.PARAMETER clientId
    Service principal application (client) ID.

.PARAMETER artifactsPath
    Folder containing the downloaded release assets (package ZIPs and settings files).

.PARAMETER configPath
    Path to the deployments/settings folder containing environment-config.json.
    Defaults to 'deployments/settings' relative to the current working directory.

.NOTES
    Requires the workflow to have `id-token: write` permission so that GitHub can issue
    an OIDC token. No client secret is needed — pac authenticates via `--githubFederated`.

    pac package deploy handles solution ordering and upgrade/override behaviour defined in
    the package's ImportConfig.xml; there is no --stage-and-upgrade equivalent at the
    package level.
#>
param(
    [Parameter(Mandatory)] [string] $packageGroup,
    [Parameter(Mandatory)] [string] $solutions,
    [Parameter(Mandatory)] [string] $targetEnvironment,
    [Parameter(Mandatory)] [string] $environmentUrl,
    [string] $tenantId = "",
    [string] $clientId = "",
    [string] $artifactsPath = "./release-assets",
    [string] $configPath = "deployments/settings"
)

$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "═══════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "  Deploy Package: $packageGroup → $targetEnvironment" -ForegroundColor Cyan
Write-Host "═══════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Environment URL : $environmentUrl"
Write-Host "  Solutions       : $solutions"
Write-Host ""

# ── Validate package/environment combination ─────────────────────────────────
$envConfigPath = Join-Path $configPath "environment-config.json"
if (Test-Path $envConfigPath) {
    $envConfig = Get-Content $envConfigPath -Raw | ConvertFrom-Json
    $group = $envConfig.packageGroups | Where-Object { $_.name -eq $packageGroup }
    if (-not $group) {
        Write-Error "Package group '$packageGroup' not found in environment-config.json."
        exit 1
    }
    $allowedEnvs = @($group.environments)
    if ($allowedEnvs.Count -gt 0 -and $targetEnvironment -notin $allowedEnvs) {
        Write-Error @"
Deployment blocked: package '$packageGroup' is not configured for environment '$targetEnvironment'.

Allowed environments for this package: $($allowedEnvs -join ', ')

To allow this deployment, add '$targetEnvironment' to the 'environments' array of the
'$packageGroup' package group in deployments/settings/environment-config.json.
"@
        exit 1
    }
    Write-Host "  ✓ Package/environment combination validated" -ForegroundColor Green
    Write-Host ""
} else {
    Write-Warning "environment-config.json not found at '$envConfigPath' — skipping package/environment guard."
}

# ── Authenticate pac CLI ────────────────────────────────────────────────────
if ($tenantId -and $clientId) {
    # GitHub Actions: federated OIDC auth
    Write-Host "Authenticating pac CLI via federated credentials (OIDC)..." -ForegroundColor Cyan
    pac auth create `
        --githubFederated `
        --tenant        $tenantId `
        --applicationId $clientId `
        --environment   $environmentUrl `
        --name          "deploy-target" | Out-Host

    if ($LASTEXITCODE -ne 0) {
        Write-Error "pac auth create failed with exit code $LASTEXITCODE."
        exit $LASTEXITCODE
    }
    Write-Host "  ✓ Authenticated via OIDC" -ForegroundColor Green
} else {
    # Local development: use existing interactive pac auth profile
    Write-Host "Using existing interactive pac auth profile" -ForegroundColor Cyan
    Write-Host "  (Run 'pac auth create --interactive --environment $environmentUrl' if not yet authenticated)" -ForegroundColor DarkGray
}

# ── Locate managed package ZIP ───────────────────────────────────────────────
$packageZip = Get-ChildItem -Path $artifactsPath -Filter "${packageGroup}_Managed_*.zip" `
    | Sort-Object LastWriteTime -Descending `
    | Select-Object -First 1

if (-not $packageZip) {
    Write-Error "No managed package ZIP found matching '${packageGroup}_Managed_*.zip' in '$artifactsPath'."
    exit 1
}
Write-Host "Package ZIP : $($packageZip.Name)" -ForegroundColor Green

# ── Build settings string from per-solution settings files ───────────────────
# Each solution in the package may have a settings file: <solution>_<version>_<env>_settings.json
# We merge all of them into a single semicolon-delimited key=value string for pac package deploy.
#
# pac solution import settings format → pac package deploy --settings format:
#   ConnectionReferences[].{ LogicalName, ConnectionId }  →  LogicalName=ConnectionId
#   EnvironmentVariables[].{ SchemaName, Value }          →  SchemaName=Value

$solutionList = $solutions -split ',' | ForEach-Object { $_.Trim() } | Where-Object { $_ }
$mergedSettings = [System.Collections.Generic.Dictionary[string,string]]::new(
    [System.StringComparer]::OrdinalIgnoreCase)

foreach ($solution in $solutionList) {
    $settingsFile = Get-ChildItem -Path $artifactsPath `
        -Filter "${solution}_*_${targetEnvironment}_settings.json" `
        | Sort-Object LastWriteTime -Descending `
        | Select-Object -First 1

    if (-not $settingsFile) {
        Write-Warning "No settings file for '$solution' / '$targetEnvironment' — skipping."
        continue
    }

    Write-Host "Settings    : $($settingsFile.Name)" -ForegroundColor Gray
    $s = Get-Content $settingsFile.FullName -Raw | ConvertFrom-Json

    foreach ($conn in @($s.ConnectionReferences)) {
        if (-not $conn -or -not $conn.LogicalName) { continue }
        if ([string]::IsNullOrWhiteSpace($conn.ConnectionId) -or
            $conn.ConnectionId -eq "00000000-0000-0000-0000-000000000000") {
            Write-Warning "  Skipping connection '$($conn.LogicalName)' — no valid ConnectionId."
            continue
        }
        $mergedSettings[$conn.LogicalName] = $conn.ConnectionId
    }

    foreach ($var in @($s.EnvironmentVariables)) {
        if (-not $var -or -not $var.SchemaName) { continue }
        if ([string]::IsNullOrWhiteSpace($var.Value)) {
            Write-Warning "  Skipping env var '$($var.SchemaName)' — empty value."
            continue
        }
        $mergedSettings[$var.SchemaName] = $var.Value
    }
}

$settingsArg = ($mergedSettings.GetEnumerator() |
    ForEach-Object { "$($_.Key)=$($_.Value)" }) -join "|"

if ($mergedSettings.Count -gt 0) {
    Write-Host "Settings    : $($mergedSettings.Count) key(s) merged from $($solutionList.Count) solution(s)" -ForegroundColor Gray
}
else {
    Write-Host "Settings    : none (deploying without runtime settings)" -ForegroundColor DarkGray
}

# ── Deploy package ────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "Deploying package..." -ForegroundColor Cyan

$deployArgs = @(
    "package", "deploy",
    "--package",    $packageZip.FullName,
    "--logConsole"
)

if (-not [string]::IsNullOrEmpty($settingsArg)) {
    $deployArgs += "--settings"
    $deployArgs += $settingsArg
}

Write-Host "  Command  : pac package deploy --package $($packageZip.Name)$(if ($settingsArg) { ' --settings <keys>' })" -ForegroundColor Gray

& pac @deployArgs

if ($LASTEXITCODE -ne 0) {
    Write-Error "pac package deploy failed with exit code $LASTEXITCODE."
    exit $LASTEXITCODE
}

Write-Host ""
Write-Host "✓ Package deployed successfully." -ForegroundColor Green
