<#
.SYNOPSIS
    Deploys individual solutions to a target Dataverse environment using pac solution import.

.DESCRIPTION
    Authenticates the pac CLI with the target environment using GitHub OIDC federated
    credentials, then imports each solution ZIP using pac solution import.

    Per-solution deployment settings files (generated by Generate-DeploymentSettings.ps1)
    are applied during import via --settings-file.

    After each successful import, post-deploy pipeline hooks are invoked via
    Invoke-PipelineHooks.ps1 (e.g., enabling flows and processes, importing config data).

    This script is called by build-deploy-solutions.yml for
    solution-level deployments (inner loop). For package-level deployments (outer loop),
    see Deploy-Package.ps1 which uses pac package deploy instead.

.PARAMETER solutionList
    Comma-separated list of solution unique names to deploy.
    Example: "pub_MySolution" or "pub_MySolution,pub_AnotherSolution"

.PARAMETER targetEnvironment
    Logical environment name (e.g. "myapp-dev"). Used to locate settings files.

.PARAMETER environmentUrl
    Target Dataverse environment URL (e.g. "https://myapp-dev-contoso.crm.dynamics.com/").

.PARAMETER tenantId
    Azure AD tenant ID.

.PARAMETER clientId
    Service principal application (client) ID.

.PARAMETER artifactsPath
    Folder containing the solution ZIPs and settings files.

.PARAMETER continueOnError
    If true, continues deploying remaining solutions when one fails.

.PARAMETER useUpgrade
    If true, uses stage-and-upgrade import (--import-as-holding followed by --apply-upgrade).
    If false, uses standard import.

.NOTES
    Requires the workflow to have `id-token: write` permission so that GitHub can issue
    an OIDC token. No client secret is needed — pac authenticates via `--githubFederated`.
#>
param(
    [Parameter(Mandatory)] [string] $solutionList,
    [Parameter(Mandatory)] [string] $targetEnvironment,
    [Parameter(Mandatory)] [string] $environmentUrl,
    [string] $tenantId = "",
    [string] $clientId = "",
    [string] $artifactsPath = "./artifacts",
    [bool]   $continueOnError = $false,
    [bool]   $useUpgrade = $false
)

$ErrorActionPreference = "Stop"

# ── Load hook manager ────────────────────────────────────────────────────────
. "$PSScriptRoot\Invoke-PipelineHooks.ps1"

$solutions = $solutionList -split ',' | ForEach-Object { $_.Trim() } | Where-Object { $_ }

Write-Host ""
Write-Host "═══════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "  Deploy Solutions → $targetEnvironment" -ForegroundColor Cyan
Write-Host "═══════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Environment URL : $environmentUrl"
Write-Host "  Solutions       : $($solutions -join ', ')"
Write-Host "  Use Upgrade     : $useUpgrade"
Write-Host "  Continue on Err : $continueOnError"
Write-Host ""

# ── Authenticate pac CLI ────────────────────────────────────────────────────
if ($tenantId -and $clientId) {
    # GitHub Actions: federated OIDC auth
    Write-Host "Authenticating pac CLI via federated credentials (OIDC)..." -ForegroundColor Cyan
    pac auth create `
        --githubFederated `
        --tenant        $tenantId `
        --applicationId $clientId `
        --environment   $environmentUrl `
        --name          "deploy-target" | Out-Host

    if ($LASTEXITCODE -ne 0) {
        Write-Error "pac auth create failed with exit code $LASTEXITCODE."
        exit $LASTEXITCODE
    }
    Write-Host "  ✓ Authenticated via OIDC" -ForegroundColor Green
} else {
    # Local development: use existing interactive pac auth profile
    Write-Host "Using existing interactive pac auth profile" -ForegroundColor Cyan
    Write-Host "  (Run 'pac auth create --interactive --environment $environmentUrl' if not yet authenticated)" -ForegroundColor DarkGray
}

# ── Track results for summary ────────────────────────────────────────────────
$hookResults = [System.Collections.Generic.List[object]]::new()
$deployResults = @()
$hasFailure = $false

# ── Deploy each solution ─────────────────────────────────────────────────────
foreach ($solution in $solutions) {
    Write-Host ""
    Write-Host "───────────────────────────────────────────────────────" -ForegroundColor DarkGray
    Write-Host "  Deploying: $solution" -ForegroundColor Cyan
    Write-Host "───────────────────────────────────────────────────────" -ForegroundColor DarkGray

    # ── Locate solution ZIP ──────────────────────────────────────────────────
    # Preference order:
    #   1. <solution>_managed.zip          (CI build, managed)
    #   2. <solution>.zip                  (exact unversioned unmanaged)
    #   3. <solution>_<version>_managed.zip (versioned managed — most recent)
    #   4. <solution>_<version>.zip         (versioned unmanaged — most recent)
    $solutionZip = Get-ChildItem -Path $artifactsPath -Filter "${solution}_managed.zip" -ErrorAction SilentlyContinue |
        Select-Object -First 1

    if (-not $solutionZip) {
        $solutionZip = Get-ChildItem -Path $artifactsPath -Filter "${solution}.zip" -ErrorAction SilentlyContinue |
            Select-Object -First 1
    }

    if (-not $solutionZip) {
        $solutionZip = Get-ChildItem -Path $artifactsPath -Filter "${solution}_*_managed.zip" -ErrorAction SilentlyContinue |
            Sort-Object LastWriteTime -Descending |
            Select-Object -First 1
    }

    if (-not $solutionZip) {
        $solutionZip = Get-ChildItem -Path $artifactsPath -Filter "${solution}_*.zip" -ErrorAction SilentlyContinue |
            Where-Object { $_.Name -notlike "*_managed.zip" } |
            Sort-Object LastWriteTime -Descending |
            Select-Object -First 1
    }

    if (-not $solutionZip) {
        $msg = "No solution ZIP found for '$solution' in '$artifactsPath'."
        if ($continueOnError) {
            Write-Warning $msg
            $deployResults += [PSCustomObject]@{ Solution = $solution; Status = "Skipped"; Error = $msg }
            continue
        }
        Write-Error $msg
        exit 1
    }

    Write-Host "  Solution ZIP : $($solutionZip.Name)" -ForegroundColor Green

    # ── Locate settings file (optional) ──────────────────────────────────────
    $settingsFile = Get-ChildItem -Path $artifactsPath `
        -Filter "${solution}_*_${targetEnvironment}_settings.json" -ErrorAction SilentlyContinue |
        Sort-Object LastWriteTime -Descending |
        Select-Object -First 1

    if ($settingsFile) {
        Write-Host "  Settings     : $($settingsFile.Name)" -ForegroundColor Gray
    }
    else {
        Write-Host "  Settings     : (none found for $targetEnvironment)" -ForegroundColor Yellow
    }

    # ── Run pre-deploy hooks ─────────────────────────────────────────────────
    $hookContext = @{
        stage                = "pre-deploy"
        solutionName         = $solution
        solutionPath         = $solutionZip.FullName
        targetEnvironment    = $targetEnvironment
        targetEnvironmentUrl = $environmentUrl
        artifactsPath        = $artifactsPath
        useSingleStageUpgrade = $useUpgrade
        tenantId             = $tenantId
        clientId             = $clientId
    }

    try {
        Invoke-PipelineHooks -Stage "Pre-Deploy" -Context $hookContext `
            -ContinueOnError:$continueOnError -Results $hookResults
    }
    catch {
        Write-Warning "Pre-deploy hooks failed for '$solution': $($_.Exception.Message)"
        if (-not $continueOnError) { exit 1 }
    }

    # ── Import solution ──────────────────────────────────────────────────────
    $deploymentStatus = "success"
    try {
        if ($useUpgrade) {
            # Stage-and-upgrade: import as holding, then apply upgrade
            Write-Host "  Importing as holding (stage-and-upgrade)..." -ForegroundColor Cyan
            $importArgs = @(
                "solution", "import",
                "--path",              $solutionZip.FullName,
                "--import-as-holding",
                "--force-overwrite",
                "--publish-changes",
                "--activate-plugins"
            )

            if ($settingsFile) {
                $importArgs += "--settings-file"
                $importArgs += $settingsFile.FullName
            }

            & pac @importArgs | Out-Host
            if ($LASTEXITCODE -ne 0) {
                throw "pac solution import --import-as-holding failed with exit code $LASTEXITCODE."
            }

            Write-Host "  Applying upgrade..." -ForegroundColor Cyan
            & pac solution import `
                --path              $solutionZip.FullName `
                --force-overwrite `
                --publish-changes `
                --activate-plugins `
                --upgrade | Out-Host

            if ($LASTEXITCODE -ne 0) {
                throw "pac solution import --upgrade failed with exit code $LASTEXITCODE."
            }
        }
        else {
            # Standard import
            Write-Host "  Importing solution..." -ForegroundColor Cyan
            $importArgs = @(
                "solution", "import",
                "--path",              $solutionZip.FullName,
                "--force-overwrite",
                "--publish-changes",
                "--activate-plugins"
            )

            if ($settingsFile) {
                $importArgs += "--settings-file"
                $importArgs += $settingsFile.FullName
            }

            & pac @importArgs | Out-Host
            if ($LASTEXITCODE -ne 0) {
                throw "pac solution import failed with exit code $LASTEXITCODE."
            }
        }

        Write-Host "  ✓ Import successful" -ForegroundColor Green
        $deployResults += [PSCustomObject]@{ Solution = $solution; Status = "Success"; Error = $null }
    }
    catch {
        $deploymentStatus = "failure"
        $hasFailure = $true
        $errorMsg = $_.Exception.Message
        Write-Host "  ✗ Import failed: $errorMsg" -ForegroundColor Red
        $deployResults += [PSCustomObject]@{ Solution = $solution; Status = "Failed"; Error = $errorMsg }

        if (-not $continueOnError) {
            exit 1
        }
    }

    # ── Run post-deploy hooks ────────────────────────────────────────────────
    $hookContext.stage = "post-deploy"
    $hookContext.deploymentStatus = $deploymentStatus

    try {
        Invoke-PipelineHooks -Stage "Post-Deploy" -Context $hookContext `
            -ContinueOnError:$continueOnError -Results $hookResults
    }
    catch {
        Write-Warning "Post-deploy hooks failed for '$solution': $($_.Exception.Message)"
        if (-not $continueOnError) { exit 1 }
    }
}

# ── Summary ──────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "═══════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "  Deployment Summary" -ForegroundColor Cyan
Write-Host "═══════════════════════════════════════════════════════" -ForegroundColor Cyan

foreach ($result in $deployResults) {
    $color = switch ($result.Status) {
        "Success" { "Green" }
        "Failed"  { "Red" }
        default   { "Yellow" }
    }
    Write-Host "  $($result.Solution): $($result.Status)" -ForegroundColor $color
    if ($result.Error) {
        Write-Host "    Error: $($result.Error)" -ForegroundColor DarkGray
    }
}

# ── Write hook summary to file (if HOOK_SUMMARY_PATH is set) ────────────────
$hookSummaryPath = $env:HOOK_SUMMARY_PATH
if ($hookSummaryPath -and $hookResults.Count -gt 0) {
    $hookSummaryDir = Split-Path -Parent $hookSummaryPath
    if ($hookSummaryDir -and -not (Test-Path $hookSummaryDir)) {
        New-Item -ItemType Directory -Path $hookSummaryDir -Force | Out-Null
    }
    $hookResults | ConvertTo-Json -Depth 5 | Set-Content -Path $hookSummaryPath -Encoding utf8
    Write-Host ""
    Write-Host "Hook summary written to: $hookSummaryPath" -ForegroundColor Gray
}

Write-Host ""
if ($hasFailure) {
    Write-Host "⚠ One or more solutions failed to deploy." -ForegroundColor Yellow
    if (-not $continueOnError) { exit 1 }
}
else {
    Write-Host "✓ All solutions deployed successfully." -ForegroundColor Green
}
